### ISSUE TITLE
error in sample

### ISSUE THREAD

**Issue by yaronn** [medialab/sandcrawler-dashboard#12]
upon running the first sample in readme I get this error:

TypeError: Object #<Sandcrawler> has no method 'spider'
    at Object.<anonymous> (/home/foo.js:4:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by Yomguithereal** [comment]
Do you mean this example?

``` js
var sandcrawler = require('sandcrawler'),
    dashboard = require('sandcrawler-dashboard');

var spider = sandcrawler.spider('MyFancySpider')
  .use(dashboard())
  .url('http://nicesite.org')
  .scraper(function($, done) {
    done(null, $('title').text());
  })
  .run();
```

If so, the error seems to mean that the required sandcrawler module is not correct. Are you sure you installed the module correctly?

Or, even, can you console.log the sandcrawler variable so we see what it contains?

**Comment by Yomguithereal** [comment]
Oh, I think I know what went wrong. The `sandcrawler` module is currently under heavy dev and is not released. So if you installed it through `npm` it won't work.

You need to install sandcrawler likewise:

```
npm install git+https://github.com/medialab/sandcrawler.git
```

**Note**: sorry for the closing/reopening. I misclicked.

**Comment by yaronn** [comment]
thanks, this works

**Comment by Yomguithereal** [comment]
Alternatively, if you want a more interesting demo, you should run `npm test`.
